INSERT INTO `auth_permission` VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO `auth_permission` VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO `auth_permission` VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO `auth_permission` VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO `auth_permission` VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO `auth_permission` VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO `auth_permission` VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO `auth_permission` VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO `auth_permission` VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO `auth_permission` VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO `auth_permission` VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO `auth_permission` VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO `auth_permission` VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO `auth_permission` VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO `auth_permission` VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO `auth_permission` VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO `auth_permission` VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO `auth_permission` VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO `auth_permission` VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO `auth_permission` VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO `auth_permission` VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO `auth_permission` VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO `auth_permission` VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO `auth_permission` VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO `auth_permission` VALUES (25, 'Can add course', 7, 'add_course');
INSERT INTO `auth_permission` VALUES (26, 'Can change course', 7, 'change_course');
INSERT INTO `auth_permission` VALUES (27, 'Can delete course', 7, 'delete_course');
INSERT INTO `auth_permission` VALUES (28, 'Can view course', 7, 'view_course');
INSERT INTO `auth_permission` VALUES (29, 'Can add department', 8, 'add_department');
INSERT INTO `auth_permission` VALUES (30, 'Can change department', 8, 'change_department');
INSERT INTO `auth_permission` VALUES (31, 'Can delete department', 8, 'delete_department');
INSERT INTO `auth_permission` VALUES (32, 'Can view department', 8, 'view_department');
INSERT INTO `auth_permission` VALUES (33, 'Can add mclass', 9, 'add_mclass');
INSERT INTO `auth_permission` VALUES (34, 'Can change mclass', 9, 'change_mclass');
INSERT INTO `auth_permission` VALUES (35, 'Can delete mclass', 9, 'delete_mclass');
INSERT INTO `auth_permission` VALUES (36, 'Can view mclass', 9, 'view_mclass');
INSERT INTO `auth_permission` VALUES (37, 'Can add source', 10, 'add_source');
INSERT INTO `auth_permission` VALUES (38, 'Can change source', 10, 'change_source');
INSERT INTO `auth_permission` VALUES (39, 'Can delete source', 10, 'delete_source');
INSERT INTO `auth_permission` VALUES (40, 'Can view source', 10, 'view_source');
INSERT INTO `auth_permission` VALUES (41, 'Can add teacher', 11, 'add_teacher');
INSERT INTO `auth_permission` VALUES (42, 'Can change teacher', 11, 'change_teacher');
INSERT INTO `auth_permission` VALUES (43, 'Can delete teacher', 11, 'delete_teacher');
INSERT INTO `auth_permission` VALUES (44, 'Can view teacher', 11, 'view_teacher');
INSERT INTO `auth_permission` VALUES (45, 'Can add student', 12, 'add_student');
INSERT INTO `auth_permission` VALUES (46, 'Can change student', 12, 'change_student');
INSERT INTO `auth_permission` VALUES (47, 'Can delete student', 12, 'delete_student');
INSERT INTO `auth_permission` VALUES (48, 'Can view student', 12, 'view_student');
INSERT INTO `auth_permission` VALUES (49, 'Can add file', 13, 'add_file');
INSERT INTO `auth_permission` VALUES (50, 'Can change file', 13, 'change_file');
INSERT INTO `auth_permission` VALUES (51, 'Can delete file', 13, 'delete_file');
INSERT INTO `auth_permission` VALUES (52, 'Can view file', 13, 'view_file');
INSERT INTO `auth_permission` VALUES (53, 'Can add image store', 14, 'add_imagestore');
INSERT INTO `auth_permission` VALUES (54, 'Can change image store', 14, 'change_imagestore');
INSERT INTO `auth_permission` VALUES (55, 'Can delete image store', 14, 'delete_imagestore');
INSERT INTO `auth_permission` VALUES (56, 'Can view image store', 14, 'view_imagestore');
INSERT INTO `auth_permission` VALUES (57, 'Can add student store', 15, 'add_studentstore');
INSERT INTO `auth_permission` VALUES (58, 'Can change student store', 15, 'change_studentstore');
INSERT INTO `auth_permission` VALUES (59, 'Can delete student store', 15, 'delete_studentstore');
INSERT INTO `auth_permission` VALUES (60, 'Can view student store', 15, 'view_studentstore');
INSERT INTO `auth_permission` VALUES (61, 'Can add student image', 16, 'add_studentimage');
INSERT INTO `auth_permission` VALUES (62, 'Can change student image', 16, 'change_studentimage');
INSERT INTO `auth_permission` VALUES (63, 'Can delete student image', 16, 'delete_studentimage');
INSERT INTO `auth_permission` VALUES (64, 'Can view student image', 16, 'view_studentimage');
INSERT INTO `auth_permission` VALUES (65, 'Can add teacher image', 17, 'add_teacherimage');
INSERT INTO `auth_permission` VALUES (66, 'Can change teacher image', 17, 'change_teacherimage');
INSERT INTO `auth_permission` VALUES (67, 'Can delete teacher image', 17, 'delete_teacherimage');
INSERT INTO `auth_permission` VALUES (68, 'Can view teacher image', 17, 'view_teacherimage');
INSERT INTO `auth_permission` VALUES (69, 'Can add admin', 18, 'add_admin');
INSERT INTO `auth_permission` VALUES (70, 'Can change admin', 18, 'change_admin');
INSERT INTO `auth_permission` VALUES (71, 'Can delete admin', 18, 'delete_admin');
INSERT INTO `auth_permission` VALUES (72, 'Can view admin', 18, 'view_admin');
INSERT INTO `auth_permission` VALUES (73, 'Can add admin image', 19, 'add_adminimage');
INSERT INTO `auth_permission` VALUES (74, 'Can change admin image', 19, 'change_adminimage');
INSERT INTO `auth_permission` VALUES (75, 'Can delete admin image', 19, 'delete_adminimage');
INSERT INTO `auth_permission` VALUES (76, 'Can view admin image', 19, 'view_adminimage');
INSERT INTO `auth_permission` VALUES (77, 'Can add teacher store', 20, 'add_teacherstore');
INSERT INTO `auth_permission` VALUES (78, 'Can change teacher store', 20, 'change_teacherstore');
INSERT INTO `auth_permission` VALUES (79, 'Can delete teacher store', 20, 'delete_teacherstore');
INSERT INTO `auth_permission` VALUES (80, 'Can view teacher store', 20, 'view_teacherstore');
INSERT INTO `auth_permission` VALUES (81, 'Can add student time', 21, 'add_studenttime');
INSERT INTO `auth_permission` VALUES (82, 'Can change student time', 21, 'change_studenttime');
INSERT INTO `auth_permission` VALUES (83, 'Can delete student time', 21, 'delete_studenttime');
INSERT INTO `auth_permission` VALUES (84, 'Can view student time', 21, 'view_studenttime');
INSERT INTO `auth_permission` VALUES (85, 'Can add student time now', 22, 'add_studenttimenow');
INSERT INTO `auth_permission` VALUES (86, 'Can change student time now', 22, 'change_studenttimenow');
INSERT INTO `auth_permission` VALUES (87, 'Can delete student time now', 22, 'delete_studenttimenow');
INSERT INTO `auth_permission` VALUES (88, 'Can view student time now', 22, 'view_studenttimenow');
INSERT INTO `auth_permission` VALUES (89, 'Can add homework', 23, 'add_homework');
INSERT INTO `auth_permission` VALUES (90, 'Can change homework', 23, 'change_homework');
INSERT INTO `auth_permission` VALUES (91, 'Can delete homework', 23, 'delete_homework');
INSERT INTO `auth_permission` VALUES (92, 'Can view homework', 23, 'view_homework');
INSERT INTO `auth_permission` VALUES (93, 'Can add work', 24, 'add_work');
INSERT INTO `auth_permission` VALUES (94, 'Can change work', 24, 'change_work');
INSERT INTO `auth_permission` VALUES (95, 'Can delete work', 24, 'delete_work');
INSERT INTO `auth_permission` VALUES (96, 'Can view work', 24, 'view_work');
INSERT INTO `auth_permission` VALUES (97, 'Can add student work', 25, 'add_studentwork');
INSERT INTO `auth_permission` VALUES (98, 'Can change student work', 25, 'change_studentwork');
INSERT INTO `auth_permission` VALUES (99, 'Can delete student work', 25, 'delete_studentwork');
INSERT INTO `auth_permission` VALUES (100, 'Can view student work', 25, 'view_studentwork');
INSERT INTO `auth_permission` VALUES (101, 'Can add student work source', 26, 'add_studentworksource');
INSERT INTO `auth_permission` VALUES (102, 'Can change student work source', 26, 'change_studentworksource');
INSERT INTO `auth_permission` VALUES (103, 'Can delete student work source', 26, 'delete_studentworksource');
INSERT INTO `auth_permission` VALUES (104, 'Can view student work source', 26, 'view_studentworksource');
