# Generated by Django 2.2.6 on 2019-11-22 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=39)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
            },
            managers=[
                ('courseManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dno', models.CharField(max_length=18, unique=True)),
                ('dname', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'department',
            },
            managers=[
                ('departmentManage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Mclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=15, unique=True)),
                ('cname', models.IntegerField()),
                ('grade', models.CharField(max_length=4)),
                ('isDelete', models.BooleanField(default=False)),
                ('con', models.ManyToManyField(to='teaching_system.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Department')),
            ],
            options={
                'db_table': 'mclass',
            },
            managers=[
                ('mclassManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10, unique=True)),
                ('sname', models.CharField(max_length=21)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'source',
            },
            managers=[
                ('sourceManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tno', models.CharField(max_length=10, unique=True)),
                ('tname', models.CharField(max_length=16)),
                ('botany', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Department')),
            ],
            options={
                'db_table': 'teacher',
            },
            managers=[
                ('teacherManage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=15, unique=True)),
                ('sname', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
                ('mclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Mclass')),
            ],
            options={
                'db_table': 'student',
            },
            managers=[
                ('studentManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fno', models.CharField(max_length=10, unique=True)),
                ('describe', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Source')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Teacher')),
            ],
            options={
                'db_table': 'file',
            },
            managers=[
                ('fileManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Teacher'),
        ),
    ]
