# Generated by Django 2.2.6 on 2019-11-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0002_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('img', models.ImageField(upload_to='course_img')),
            ],
            options={
                'db_table': 'ImageStore',
            },
        ),
    ]
