# Generated by Django 2.2.6 on 2019-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0003_imagestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
