# Generated by Django 2.2.6 on 2019-11-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0004_course_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fno',
        ),
    ]
