# Generated by Django 2.2.6 on 2019-11-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0005_remove_file_fno'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
