# Generated by Django 2.2.6 on 2019-11-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0007_course_dno'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Course'),
            preserve_default=False,
        ),
    ]
