# Generated by Django 2.2.6 on 2019-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0008_file_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
