# Generated by Django 2.2.6 on 2019-11-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0009_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
