# Generated by Django 2.2.6 on 2019-11-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0010_remove_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('src', models.ImageField(upload_to='studentStore')),
            ],
            options={
                'db_table': 'studentStore',
            },
        ),
    ]
