# Generated by Django 2.2.6 on 2019-11-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0012_auto_20191201_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mclass',
            name='cno',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
