# Generated by Django 2.2.6 on 2019-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0013_auto_20191201_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mclass',
            name='grade',
            field=models.CharField(max_length=6),
        ),
    ]
