# Generated by Django 2.2.6 on 2019-12-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0015_auto_20191201_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mclass',
            name='con',
        ),
        migrations.AddField(
            model_name='mclass',
            name='con',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Course'),
            preserve_default=False,
        ),
    ]
