# Generated by Django 2.2.6 on 2019-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0019_adminimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('src', models.ImageField(upload_to='teacherStore')),
            ],
            options={
                'db_table': 'teacherStore',
            },
        ),
    ]
