# Generated by Django 2.2.6 on 2019-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0020_teacherstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
