# Generated by Django 2.2.6 on 2019-12-19 14:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0022_auto_20191209_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=30)),
                ('timelong', models.FloatField()),
                ('time', models.CharField(max_length=10)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'studentTime',
            },
            managers=[
                ('studentTimeManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentTimeNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'studentTimeNow',
            },
            managers=[
                ('studentTimeNowManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
