# Generated by Django 2.2.6 on 2019-12-22 00:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0023_studenttime_studenttimenow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Source')),
            ],
            options={
                'db_table': 'homework',
            },
            managers=[
                ('homeworkManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('hno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Homework')),
            ],
            options={
                'db_table': 'work',
            },
            managers=[
                ('WorkManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
