# Generated by Django 2.2.6 on 2019-12-27 00:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0024_homework_work'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='work',
            managers=[
                ('workManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.CharField(max_length=15),
        ),
    ]
