# Generated by Django 2.2.6 on 2020-01-08 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0025_auto_20191227_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeWorkStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('src', models.ImageField(upload_to='student_homework')),
            ],
            options={
                'db_table': 'student_homework',
            },
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_submitDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Student')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.Homework')),
            ],
            options={
                'db_table': 'studentworkManager',
            },
            managers=[
                ('studentWorkManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentWorkSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('workmanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_system.StudentWork')),
            ],
            options={
                'db_table': 'studentworksource',
            },
            managers=[
                ('studentWorkSourceManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
