# Generated by Django 2.2.6 on 2020-01-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_system', '0026_studenthomeworkstore_studentwork_studentworksource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentHomeWorkStore',
        ),
    ]
